// ==================== BASE TYPES ===================

export interface Property {
  id: number;
  p_id: string | null;
  project_id: number | null;
  listing_type: string | null;
  occupancy: string | null;
  qc: string | null;
  dld_permit: string | null;
  views: string | null;
  bathrooms: string | null;
  title_deep: string | null;
  Spa_number: string | null;
  from_duration: string | null;
  to_duration: string | null;
  availability_type: string | null;
  RefNumber: string | null;
  user_id: number | null;
  developer: number | null;
  featured_property: string | null;
  property_name: string | null;
  keyword: string | null;
  seo_title: string | null;
  meta_description: string | null;
  canonical_tags: string | null;
  property_slug: string | null;
  property_type: string | null;
  location: string | null;
  property_purpose: string | null;
  address: string | null;
  map_latitude: string | null;
  map_longitude: string | null;
  pincode: string | null;
  landmark: string | null;
  country: string | null;
  state_id: number | null;
  city_id: number | null;
  community_id: number | null;
  sub_community_id: number | null;
  agent_id: number | null;
  building: string | null;
  description: string | null;
  property_features: string | null;
  featured_image: string | null;
  floor_media_ids: string | null;
  gallery_media_ids: string | null;
  developer_id: number | null;
  video_url: string | null;
  whatsapp_url: string | null;
  flooring: string | null;
  furnishing: string | null;
  video_code: string | null;
  price: number | null;
  price_end: string | null;
  askprice: string | null;
  currency_id: number | null;
  bedroom: string | null;
  kitchen_room: number | null;
  guest_room: number | null;
  other_room: number | null;
  total_room: string | null;
  floor_no: number | null;
  lift: number | null;
  max_area: string | null;
  min_area: string | null;
  area: number | null;
  area_end: string | null;
  area_size: string | null;
  amenities: string | null;
  parking: string | null;
  property_status: string | null;
  ReraNumber: string | null;
  unit: string | null;
  complete_date: Date | null;
  listing_agent_id: number | null;
  modify_by_admin: number | null;
  identifying_channel: string | null;
  marketing_channel: string | null;
  contact_channel: string | null;
  owner_id: number | null;
  owner_developer_id: string | null;
  owner_agreement: string | null;
  owner_commision: string | null;
  owner_creation_date: Date | null;
  owner_listing_date: Date | null;
  exclusive_status: string | null;
  completion_date: string | null;
  vacating_date: string | null;
  documents_id: string | null;
  status: number;
  created_at: Date | null;
  updated_at: Date | null;
  more_filter: string | null;
  property_locations: string | null;
}

export interface PropertyWithRelations extends Property {
  property_type_name?: string;
  property_type_slug?: string;
  developer_name?: string;
  developer_logo?: string;
  agent_name?: string;
  agent_phone?: string;
  agent_photo?: string;
  agent_rera?: string;
  community_name?: string;
  community_slug?: string;
  community_image?: string;
  sub_community_name?: string;
  state_name?: string;
  city_name?: string;
  country_name?: string;
  latitude?: string;
  longitude?: string;
  unit_number?: string;
  floor_number?: string;
  currency_code?: string;
  currency_symbol?: string;
  images?: Media[];
  prices?: PropertyPrice[];
  facilities?: Facility[];
  payment_plans?: PaymentPlan[];
}

export interface Media {
  id: number;
  module_id: number | null;
  module_type: string | null;
  module_sub_type: string | null;
  featured: number | null;
  path: string | null;
  title: string | null;
  sub_title: string | null;
  description: string | null;
  media_order: number | null;
  status: number;
  update_date: Date;
}

export interface PropertyPrice {
  id: number;
  property_id: number;
  type: string | null;
  number_of_cheques: string | null;
  diposit_amount: string | null;
  agency_fee: string | null;
  rental_per_year: string | null;
  viewing_time: string | null;
  viewing_possible_rental: string | null;
  viewing_possible_sale: string | null;
  rental_price: string | null;
  sale_price: string | null;
  listing_price: string | null;
  currency_id: number | null;
  rental_period: string | null;
  price_on_application: number | null;
  commision_from_landlord: string | null;
  payment_plan_ids: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface PaymentPlan {
  id: number;
  item_id: number | null;
  item_type: string | null;
  name: string | null;
  percentage: string | null;
  status: number | null;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface Facility {
  id: number;
  property_id: number | null;
  type: string | null;
  kitchen_open_plan: string | null;
  kitchen_closed: string | null;
  back_kitchen: string | null;
  dry_pantry: string | null;
  maid_quarters: string | null;
  maid_quarters_qty: string | null;
  driver_quarters: string | null;
  storage_room: string | null;
  storage_room_qty: string | null;
  laundry_room: string | null;
  study_room: string | null;
  study_room_qty: string | null;
  games_room: string | null;
  library: string | null;
  cinema_room: string | null;
  landing_area: string | null;
  wine_cellar: string | null;
  terraces: string | null;
  balconies: string | null;
  balconies_qty: string | null;
  basement: string | null;
  furnished: string | null;
  furnish_type: string | null;
  built_in_wardrobes: string | null;
  built_in_wardrobes_qty: string | null;
  walk_in_closets: string | null;
  smart_home_technology: string | null;
  equipped_kitchen: string | null;
  kitchen_Countertops_tile: string | null;
  flooring_tile: string | null;
  equipped_laundry: string | null;
  reception_service: string | null;
  concierge_service: string | null;
  valet_parking: string | null;
  swimming_pool: string | null;
  swimming_pool_private: string | null;
  swimming_pool_communal: string | null;
  swimming_pool_overflow: string | null;
  swimming_pool_heated: string | null;
  swimming_pool_infinity: string | null;
  swimming_pool_cooled: string | null;
  swimming_pool_standard: string | null;
  swimming_pool_both: string | null;
  Jacuzzi: string | null;
  steam_room: string | null;
  sauna: string | null;
  gymnasium: string | null;
  gymnasium_private: string | null;
  gymnasium_communal: string | null;
  gymnasium_both: string | null;
  tennis_court: string | null;
  squash_court: string | null;
  basketball_court: string | null;
  golf_course: string | null;
  bbo: string | null;
  private_elevator: string | null;
  child_play_area: string | null;
  allocated_parking: string | null;
  allocated_parking_qty: string | null;
  add_any_additional_amenties: string | null;
  create_date: Date | null;
  update_date: Date;
  status: number;
}

export interface Developer {
  id: number;
  name: string | null;
  year_established: string | null;
  country: string | null;
  website: string | null;
  responsible_agent: string | null;
  ceo_name: string | null;
  email: string | null;
  mobile: string | null;
  address: string | null;
  image: string | null;
  total_project: string | null;
  total_project_withus: string | null;
  total_url: string | null;
  informations: string | null;
  seo_title: string | null;
  seo_keywork: string | null;
  seo_description: string | null;
  created_at: Date | null;
  updated_at: Date | null;
  status: number;
}

export interface User {
  id: number;
  usertype: string | null;
  cuid: string | null;
  treatment: string | null;
  department: string | null;
  length_of_service: string | null;
  full_name: string | null;
  name: string | null;
  rera_brn: string | null;
  orn_number: string | null;
  email: string | null;
  other_email: string | null;
  password: string | null;
  provider_id: string | null;
  provider: string | null;
  phone: string | null;
  about: string | null;
  mobile_phone: string | null;
  salutation: string | null;
  licence: string | null;
  photo: string | null;
  resume: string | null;
  fax: string | null;
  country: number | null;
  city: string | null;
  facebook: string | null;
  twitter: string | null;
  gplus: string | null;
  linkedin: string | null;
  website: string | null;
  fixed_salary: string | null;
  basic_commision: string | null;
  over_target_commission: string | null;
  recruiting: string | null;
  joining_date: Date | null;
  leaving_date: Date | null;
  public_permision: number;
  educatin: string | null;
  category: string;
  image_icon: string | null;
  seo_title: string | null;
  seo_keywork: string | null;
  seo_description: string | null;
  confirmation_code: string | null;
  remember_token: string | null;
  created_at: Date | null;
  updated_at: Date | null;
  status: number;
  first_login: string | null;
  nationality: string | null;
  marital_status: string | null;
  originality: string | null;
  languages: string | null;
  contact_type: string | null;
  instagram: string | null;
  dob: string | null;
  first_name: string | null;
  last_name: string | null;
  marketing_name: string | null;
  full_legal_name: string | null;
  gender: string | null;
  first_name_2: string | null;
  last_name_2: string | null;
  mobile_phone2: number | null;
}

export interface Community {
  id: number;
  community_id: number | null;
  name: string;
  country_id: number;
  state_id: number | null;
  city_id: number;
  slug: string | null;
  latitude: string | null;
  longitude: string | null;
  img: string | null;
  school_img: string | null;
  hotel_img: string;
  hospital_img: string | null;
  train_img: string | null;
  bus_img: string | null;
  description: string | null;
  top_community: string | null;
  top_projects: string | null;
  featured_project: string | null;
  related_blog: string | null;
  properties: string | null;
  similar_location: string | null;
  sales_diretor: string | null;
  seo_slug: string | null;
  seo_title: string | null;
  seo_keywork: string | null;
  seo_description: string | null;
  featured: number | null;
  status: number;
}

export interface Project {
  id: number;
  user_id: number | null;
  state_id: string | null;
  city_id: string | null;
  community_id: string | null;
  sub_community_id: string | null;
  listing_type: string | null;
  occupancy: string | null;
  qc: string | null;
  completion_date: string | null;
  vacating_date: string | null;
  exclusive_status: string | null;
  property_ids: string | null;
  floor_media_ids: string | null;
  gallery_media_ids: string | null;
  developer_id: number | null;
  ProjectId: string | null;
  ProjectNumber: string | null;
  MemberId: number | null;
  ProjectName: string | null;
  Description: string | null;
  featured_project: string | null;
  dld_permit: string | null;
  views: string | null;
  title_deep: string | null;
  Spa_number: string | null;
  from_duration: string | null;
  to_duration: string | null;
  availability_type: string | null;
  price: string | null;
  price_end: string | null;
  askprice: string | null;
  currency_id: number | null;
  property_type: string | null;
  unit: string | null;
  bedroom: string | null;
  area: string | null;
  area_end: string | null;
  area_size: string | null;
  agent_id: string | null;
  Specifications: string | null;
  StartDate: string | null;
  EndDate: string | null;
  BuildingName: string | null;
  StreetName: string | null;
  LocationName: string | null;
  CityName: string | null;
  StateName: string | null;
  PinCode: string | null;
  LandMark: string | null;
  country: string | null;
  floors: number | null;
  rooms: number | null;
  total_building: number | null;
  kitchen_type: string | null;
  amenities: string | null;
  Vaastu: number | null;
  Lift: number | null;
  Club: number | null;
  RainWaterHaresting: number | null;
  PowerBackup: number | null;
  GasConnection: number | null;
  SwimmingPool: number | null;
  Parking: number | null;
  Security: number | null;
  InternetConnection: number | null;
  Gym: number | null;
  ServantQuarters: number | null;
  Balcony: number | null;
  PlayArea: number | null;
  CCTV: number | null;
  ReservedPark: number | null;
  Intercom: number | null;
  Lawn: number | null;
  Terrace: number | null;
  Garden: number | null;
  EarthquakeConstruction: number | null;
  LogoUrl: string | null;
  Url: string | null;
  video_url: string | null;
  whatsapp_url: string | null;
  featured_image: string | null;
  IsFeatured: string | null;
  LastUpdated: string | null;
  keyword: string | null;
  seo_title: string | null;
  meta_description: string | null;
  canonical_tags: string | null;
  project_slug: string | null;
  listing_agent_id: string | null;
  identifying_channel: string | null;
  marketing_channel: string | null;
  contact_channel: string | null;
  owner_id: string | null;
  owner_developer_id: string | null;
  owner_agreement: string | null;
  owner_commision: string | null;
  owner_creation_date: Date | null;
  owner_listing_date: Date | null;
  documents_id: string | null;
  status: number | null;
  verified: number | null;
  template: number;
  created_at: Date | null;
  updated_at: Date | null;
}

// ==================== API RESPONSE TYPES ====================

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message?: string;
  meta?: {
    total?: number;
    page?: number;
    limit?: number;
    totalPages?: number;
  };
}

export interface SearchFilters {
  property_type?: string;
  property_purpose?: string;
  city_id?: number;
  community_id?: number;
  sub_community_id?: number;
  min_price?: number;
  max_price?: number;
  min_bedrooms?: number;
  max_bedrooms?: number;
  min_area?: number;
  max_area?: number;
  listing_type?: string;
  status?: number;
  featured?: boolean;
  keyword?: string;
  sort_by?: 'price_asc' | 'price_desc' | 'newest' | 'oldest';
  page?: number;
  limit?: number;
}

export interface EnquiryData {
  property_id: number;
  name: string;
  email: string;
  phone: string;
  message?: string;
  user_id?: number | null;
}

export interface ContactData {
  name: string;
  email: string;
  phone: string;
  subject: string;
  message: string;
}